spring:
  datasource:
  url: "jdbc:postgresql://localhost:5432/users"
  username: app_user
  password: app_password
  driver-class-name: "org.postgresql.Driver"
  flyway:
    url: "jdbc:postgresql://localhost:5432/users"
    user: flyway_user
    password: flyway_password
    placeholders:
      dbAppUser: app_user
      dbAppPassword: app_password
